[tool.black]
target-version = ['py310']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "nlp"
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.coverage.run]
source = ["nlp/"]
omit = ["nlp/__main__.py"]

[tool.coverage.report]
skip_covered = true
show_missing = true
ignore_errors = true
fail_under = 100
exclude_lines = ['def __repr__', 'class .*\bProtocol\):']
