repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0
    hooks:
      - id: isort
        name: isort-api
        entry: isort api
        pass_filenames: false
      - id: isort
        name: isort-cli
        entry: isort cli
        pass_filenames: false
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        args: ["--max-line-length=89"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        name: mypy-api
        entry: mypy api/app
        pass_filenames: false
      - id: mypy
        name: mypy-cli
        entry: mypy cli/aita
        pass_filenames: false
