language: python
python:
  - "3.7"

services:
  - docker

before_script:
  pip install docker-compose

script:
  - docker-compose -f docker-compose.test.yml up -d
  - docker-compose exec api pytest .
