language: python
python:
  - "3.7"

services:
  - docker

before_script:
  pip install docker-compose

env:
  - FILE=docker-compose.test.yml

script:
  - docker-compose -f $FILE up -d
  - docker-compose -f $FILE exec api pytest tests
