language: python
python:
  - "3.7"

services:
  - docker

before_script:
  - pip install -U pip setuptools
  - pip install docker docker-compose mypy flake8

script:
  - mypy --ignore-missing-imports ./api
  - mypy --ignore-missing-imports ./cli
  - flake8 --max-line-length=88 ./api ./cli
  - docker volume prune -f
  - docker-compose pull
  - docker-compose up -d api
  - sleep 10
  - docker-compose exec api pytest -v tests
  - docker-compose down -v
