language: python
python:
  - "3.7"

services:
  - docker

before_script:
  - pip install -U pip setuptools
  - pip install pre-commit
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker volume prune -f
  - docker-compose pull api
  - docker-compose up -d api

script:
  - pre-commit run --all-files
  - docker-compose exec api pytest -v tests
  - docker-compose down -v
