version: "3.7"

services:
  db:
    image: postgres:12.1-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-aita}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-aita}
      - POSTGRES_DB=${POSTGRES_DB:-aita_db}

  api:
    build:
      context: api
      target: development
    image: lvconnolly/aita_api:dev
    ports:
      - ${API_PORT:-8000}:8000
    volumes:
      - ./api:/usr/src/app
    environment:
      - ENV=${ENV:-dev}
      - POSTGRES_USER=${POSTGRES_USER:-aita}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-aita}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_DB=${POSTGRES_DB:-aita_db}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
    depends_on:
      - db

volumes:
  postgres_data:
