version: '3.7'


services:

  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB} 

  cli:
    build: ./aita
    image: lvconnolly/aita_cli:alpine3.10
    tty: true
    volumes:
      - ./aita:/app
    environment:
      - API_HOST=${API_HOST}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
    links:
      - "api:api"

  api:
    build: ./api
    image: lvconnolly/aita_api:alpine3.10
    ports:
      - ${API_PORT}:8000
    volumes:
      - ./api:/app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
    command: uvicorn app.main:app --reload --host 0.0.0.0
    depends_on:
      - db


volumes:
    postgres_data:
