version: "3.7"

services:
  db:
    image: postgres:12.1-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  api:
    build:
      context: api
    image: lvconnolly/aita_api:dev
    ports:
      - ${API_PORT}:8000
      - 5678:5678
    volumes:
      - ./api:/app
    environment:
      - DEBUG=${DEBUG}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
    depends_on:
      - db

volumes:
  postgres_data:
