version: '3.7'


services:

  api:
    build: ./api
    image: aita_api:dev
    volumes:
      - ./api:/app
    ports:
      - ${API_PORT}:80
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - TESTING=${TESTING}

  cli:
    build: ./cli
    image: aita_cli:dev
    volumes:
      - ./cli:/app/
    environment:
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
    links:
      - "api:api"
        
  db:
    image: postgres:12.1-alpine
    volumes:
    - ./scripts/pg-init-scripts:/docker-entrypoint-initdb.d
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_MULTIPLE_DATABASE=${POSTGRES_DB},${POSTGRES_DB}_test


volumes:
    postgres_data:
