version: "3.7"

services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  api:
    build:
      context: api
    image: lvconnolly/aita_api:dev
    ports:
      - ${API_PORT}:80
      - 5678:5678
    volumes:
      - ./api:/app
    environment:
      - DEBUG=${DEBUG}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
      - WEB_PORT=${WEB_PORT}
    command: /start-reload.sh
    depends_on:
      - db

  web:
    build:
      context: web
      target: develop-stage
    image: lvconnolly/aita_web:dev
    ports:
      - ${WEB_PORT}:3000
    volumes:
      - ./web:/srv/app
    environment:
      - HOST=0.0.0.0
    command: /bin/sh -c "npm run dev"
    depends_on:
      - api

volumes:
  postgres_data:
