[tool.black]
target-version = ['py38']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.mypy]
plugins = 'sqlalchemy.ext.mypy.plugin'
exclude = ['app/db/migrations/', 'tests/']
