[tool.poetry]
name = "api"
version = "0.1.0"
description = "Fastapi api for processing reddit posts from /r/AmItheAsshole"
authors = ["Logan Connolly <logan.connolly@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.63.0"
orm = "^0.1.5"
asyncpg = "^0.20.1"
uvicorn = "^0.11.5"
psycopg2-binary = "^2.8.5"
loguru = "^0.4.1"
alembic = "^1.4.3"
praw = "^7.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
requests = "^2.25.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
